### ISSUE TITLE
Suiteslicing mechanizm cannot load scenarios: "URI is not hierarchical"

### ISSUE THREAD

**Issue by scormaq** [serenity-bdd/serenity-cucumber4#21]
I applied parallelization mechanizm, described in [documentation](https://serenity-bdd.github.io/theserenitybook/latest/serenity-parallel-batches.html), to run Cucumber features in parallel within single computer instance. Worked fine for next versions:
```
serenity_version = '2.0.70'
serenity_cucumber4_version = '1.0.21'
cucumber_version = '4.2.0'
```
Sliced runner classes looks like next:
```java
package foo.bar;

import org.junit.runner.RunWith;

// deprecated package BTW
import cucumber.api.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;

@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
    plugin = {"foo.bar.GradleForkHelper"},
    glue = "foo.bar.cucumber",
    features = "classpath:features"
)
public class AcceptanceTestsFork1 {
}
```

After upgrade to latest versions
```
serenity_version = '2.0.90'
serenity_cucumber4_version = '1.0.29'
cucumber_version = '4.8.0'
```

Suite slicing mechanizm now fails with exception:
```
foo.bar.AcceptanceTestsFork2 STANDARD_OUT
    [ERROR][2019-12-20 15:05:08] Test failed to start
    java.lang.IllegalStateException: Could not extract scenarios from classpath:features/test_feature.feature
        at net.serenitybdd.cucumber.suiteslicing.CucumberScenarioLoader.lambda$getScenarios$2(CucumberScenarioLoader.java:67) ~[serenity-cucumber4-1.0.29.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at net.serenitybdd.cucumber.suiteslicing.CucumberScenarioLoader.load(CucumberScenarioLoader.java:47) ~[serenity-cucumber4-1.0.29.jar:?]
        at net.serenitybdd.cucumber.suiteslicing.CucumberSuiteSlicer.scenarios(CucumberSuiteSlicer.java:22) ~[serenity-cucumber4-1.0.29.jar:?]
        at io.cucumber.junit.CucumberSerenityRunner.getChildren(CucumberSerenityRunner.java:281) [serenity-cucumber4-1.0.29.jar:?]
        at org.junit.runners.ParentRunner.getFilteredChildren(ParentRunner.java:426) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:351) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner.run(ParentRunner.java:359) [junit-4.12.jar:4.12]
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110) [gradle-testing-jvm-5.4.jar:5.4]
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58) [gradle-testing-jvm-5.4.jar:5.4]
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38) [gradle-testing-jvm-5.4.jar:5.4]
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62) [gradle-testing-jvm-5.4.jar:5.4]
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51) [gradle-testing-base-5.4.jar:5.4]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35) [gradle-messaging-5.4.jar:5.4]
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24) [gradle-messaging-5.4.jar:5.4]
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32) [gradle-messaging-5.4.jar:5.4]
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93) [gradle-messaging-5.4.jar:5.4]
        at com.sun.proxy.$Proxy5.processTestClass(Unknown Source) [?:?]
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118) [gradle-testing-base-5.4.jar:5.4]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35) [gradle-messaging-5.4.jar:5.4]
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24) [gradle-messaging-5.4.jar:5.4]
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175) [gradle-messaging-5.4.jar:5.4]
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157) [gradle-messaging-5.4.jar:5.4]
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404) [gradle-messaging-5.4.jar:5.4]
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63) [gradle-base-services-5.4.jar:5.4]
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46) [gradle-base-services-5.4.jar:5.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55) [gradle-base-services-5.4.jar:5.4]
        at java.lang.Thread.run(Thread.java:834) [?:?]
    Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
        at java.io.File.<init>(File.java:418) ~[?:?]
        at net.serenitybdd.cucumber.suiteslicing.CucumberScenarioLoader.lambda$null$1(CucumberScenarioLoader.java:59) ~[serenity-cucumber4-1.0.29.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at net.serenitybdd.cucumber.suiteslicing.CucumberScenarioLoader.lambda$getScenarios$2(CucumberScenarioLoader.java:65) ~[serenity-cucumber4-1.0.29.jar:?]
        ... 43 more
```

Edit: OS is Windows 10

**Comment by wakaleo** [comment]
Batches are probably not compatible with Cucumber 4 parallel processing. I’m not familiar with the code so you might need to ask @nbarrett

**Comment by scormaq** [comment]
Works fine in serenity-cucumber4 1.0.30
